INSERT INTO customers (username, subscriptionTier, fName, lName, streetAddress, city, country, active90)
VALUES
('coolCat123', 'free','Liam', 'Smith', '123 Maple Street', 'Springfield','United States', False),
('stormySky_2023', 'paid','Emma', 'Johnson', '456 Oak Avenue', 'Riverdale','United States', False),
('happyPenguin99', 'power','Noah', 'Williams', '789 Pine Road', 'Pleasantville','United States', True),
('mysticWizard77', 'free','Olivia', 'Jones', '321 Elm Drive', 'Hilltop','United States', False),
('swiftFox_88', 'paid','Oliver', 'Brown', '654 Birch Lane', 'Cedar City','United States', True),
('oceanDreamer21', 'power','Ava', 'Davis', '987 Cherry Blvd', 'Sunnyvale','United States', True),
('techGiant_45', 'free','Elijah', 'Miller', '135 Walnut Street', 'Maplewood','United States', True),
('greenThumbedArtist', 'paid','Sophia', 'Wilson', '246 Ash Road', 'Greenfield','United States', True),
('starryNights_22', 'power','James', 'Moore', '357 Cedar Avenue', 'Oak Ridge','United States', False),
('fuzzyBunny_92', 'free','Isabella', 'Taylor', '468 Sycamore Lane', 'Brookside','United States', True),
('loneWolf_101', 'paid','William', 'Anderson', '579 Magnolia Blvd', 'Westfield','United States', True),
('adventurousSpirit', 'power','Mia', 'Thomas', '680 Spruce Street', 'Fairview','United States', False),
('quirkyGiraffe_07', 'free','Benjamin', 'Jackson', '791 Redwood Drive', 'Newtown','United States', False),
('vintageTraveler_9', 'paid','Charlotte', 'White', '802 Fir Road', 'Lakewood','United States', True),
('boldExplorer34', 'power','Lucas', 'Harris', '913 Palm Avenue', 'Meadowbrook','United States', True),
('creativeCoder_88', 'free','Amelia', 'Martin', '124 Peach Street', 'Glenwood','United States', False),
('glitteringGalaxy', 'paid','Henry', 'Thompson', '235 Lemon Lane', 'Riverview','United States', True),
('cheeryBreeze_25', 'power','Harper', 'Garcia', '346 Coconut Blvd', 'Silverlake','United States', False),
('quietMountain_17', 'free','Alexander', 'Martinez', '457 Olive Drive', 'Mountainview','United States', False),
('daringDolphin_33', 'paid','Evelyn', 'Robinson', '568 Fig Road', 'Star City','United States', False),
('electricEagle21', 'power','Jackson', 'Clark', '679 Apricot Street', 'Pine Hill','United States', False),
('whimsicalSparrow', 'free','Abigail', 'Rodriguez', '780 Pecan Avenue', 'Maple Grove','United States', False),
('sunsetDreamer_54', 'paid','Sebastian', 'Lewis', '891 Hazel Lane', 'Crystal Lake','United States', True),
('jollyJester_11', 'power','Ella', 'Lee', '902 Kiwi Blvd', 'Harmony','United States', True),
('techSavvy_007', 'free','Aiden', 'Walker', '213 Raspberry Road', 'Summerfield','United States', False),
('mellowMelody_19', 'paid','Scarlett', 'Hall', '324 Blackberry Drive', 'Brighton','United States', False),
('brightStar_2024', 'power','Matthew', 'Allen', '435 Blueberry Street', 'Crestwood','United States', True),
('curiousOwl_40', 'free','Grace', 'Young', '546 Watermelon Avenue', 'Elmwood','United States', False),
('dancingDragon_16', 'paid','Samuel', 'Hernandez', '657 Tangerine Lane', 'Oak Valley','United States', True),
('happyTraveler_66', 'power','Chloe', 'King', '768 Grapefruit Blvd', 'Pinewood','United States', True),
('charmingChameleon', 'free','David', 'Wright', '879 Avocado Drive', 'Riverbend','United States', True),
('caffeineQueen_12', 'paid','Sofia', 'Lopez', '980 Cucumber Street', 'Brookhaven','United States', False),
('mysterySeeker_07', 'power','Joseph', 'Hill', '101 Lettuce Avenue', 'Meadowlark','United States', True),
('vividVoyager_22', 'free','Aria', 'Scott', '202 Zucchini Lane', 'Hillcrest','United States', False),
('puzzledPanda_33', 'paid','Carter', 'Green', '303 Carrot Blvd', 'Evergreen','United States', True),
('urbanNomad_18', 'power','Mila', 'Adams', '404 Radish Road', 'Willow Creek','United States', False),
('colorfulCanvas_4', 'free','Isaiah', 'Baker', '505 Potato Street', 'Green Hills','United States', True),
('silentScribe_23', 'paid','Zoe', 'Gonzalez', '606 Squash Avenue', 'Silver Springs','United States', True),
('whirlwind_Artist', 'power','Gabriel', 'Nelson', '707 Pumpkin Lane', 'Maple Leaf','United States', True),
('zestyZebra_45', 'free','Nora', 'Carter', '808 Spinach Blvd', 'Lakeside','United States', False),
('dreamyDaisy_2024', 'paid','Anthony', 'Mitchell', '909 Kale Drive', 'Ridgeway','United States', False);
