INSERT INTO serviceOfferings (offeringTitle, offeredBy)
VALUES
('offering1', 'Web Hosting'),
('offering2', 'Web Hosting'),
('offering3', 'Web Hosting'),
('offering4', 'Web Hosting'),
('offering5', 'Web Hosting'),
('offering1', 'Cloud Storage'),
('offering2', 'Cloud Storage'),
('offering3', 'Cloud Storage'),
('offering4', 'Cloud Storage'),
('offering5', 'Cloud Storage'),
('offering1', 'Email Marketing'),
('offering2', 'Email Marketing'),
('offering3', 'Email Marketing'),
('offering4', 'Email Marketing'),
('offering5', 'Email Marketing'),
('offering1', 'SEO Optimization'),
('offering2', 'SEO Optimization'),
('offering3', 'SEO Optimization'),
('offering4', 'SEO Optimization'),
('offering5', 'SEO Optimization'),
('offering1', 'Social Media Management'),
('offering2', 'Social Media Management'),
('offering3', 'Social Media Management'),
('offering4', 'Social Media Management'),
('offering5', 'Social Media Management'),
('offering1', 'Online Payment Processing'),
('offering2', 'Online Payment Processing'),
('offering3', 'Online Payment Processing'),
('offering4', 'Online Payment Processing'),
('offering5', 'Online Payment Processing'),
('offering1', 'Graphic Design'),
('offering2', 'Graphic Design'),
('offering3', 'Graphic Design'),
('offering4', 'Graphic Design'),
('offering5', 'Graphic Design'),
('offering1', 'Content Creation'),
('offering2', 'Content Creation'),
('offering3', 'Content Creation'),
('offering4', 'Content Creation'),
('offering5', 'Content Creation'),
('offering1', 'Virtual Assistant Services'),
('offering2', 'Virtual Assistant Services'),
('offering3', 'Virtual Assistant Services'),
('offering4', 'Virtual Assistant Services'),
('offering5', 'Virtual Assistant Services'),
('offering1', 'IT Support'),
('offering2', 'IT Support'),
('offering3', 'IT Support'),
('offering4', 'IT Support'),
('offering5', 'IT Support'),
('offering1', 'Data Backup Solutions'),
('offering2', 'Data Backup Solutions'),
('offering3', 'Data Backup Solutions'),
('offering4', 'Data Backup Solutions'),
('offering5', 'Data Backup Solutions'),
('offering1', 'Website Development'),
('offering2', 'Website Development'),
('offering3', 'Website Development'),
('offering4', 'Website Development'),
('offering5', 'Website Development'),
('offering1', 'Digital Marketing'),
('offering2', 'Digital Marketing'),
('offering3', 'Digital Marketing'),
('offering4', 'Digital Marketing'),
('offering5', 'Digital Marketing'),
('offering1', 'App Development'),
('offering2', 'App Development'),
('offering3', 'App Development'),
('offering4', 'App Development'),
('offering5', 'App Development'),
('offering1', 'Consulting Services');
